name: Prettier-linter 

# Ref: https://github.com/marketplace/actions/prettier-action
# This action only runs on front-end changed files  
on:
  push:
    branches:
      - dev

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prettify code
        uses: creyD/prettier_action@v4.5
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md,svelte}
          only_changed: True
