name: Ruff-Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Apparently Required for proper commit history

      - name: Run Ruff (lint + format)
        uses: astral-sh/ruff-action@v3
        with:
          args: --fix --format  # Combines linting and formatting
          
      - name: Commit fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Fix linting issues with Ruff"
          branch: ${{ github.head_ref }}  # Important for PRs