name: Run-Tests
on:
  push:
    branches: [ main, dev, repo_maintenance ]
  pull_request:
    branches: [ main, dev, repo_maintenance ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.13' ]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: 0.5.7

      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras

      - name: Run tests
        env: 
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_S3_REGION_NAME: ${{ env.AWS_S3_REGION_NAME }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        run: | #Tests are internal to the application currently.
          cd commonthread
          uv run pytest
